-- File: test_top.vhd
-- Generated by MyHDL 0.11
-- Date: Mon Feb 24 14:23:10 2020


library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use std.textio.all;

use work.pck_myhdl_011.all;

entity test_top is
end entity test_top;


architecture MyHDL of test_top is


signal segdp: std_logic;
signal seg: unsigned(12 downto 0);
signal oled: unsigned(7 downto 0);
signal clk_in: std_logic := '0';
signal reset_n: std_logic;
begin


clk_in <= not clk_in after 10 ns;


TEST_TOP_START: process is
begin
    wait for 10 * 1 ns;
    reset_n <= '0';
    wait for 100 * 1 ns;
    reset_n <= '1';
    wait for 10 * 1 ns;
    wait;
end process TEST_TOP_START;

uut: entity work.top
	port map (
        rxd_uart   => 'H',
        txd_uart   => 'H',
        oled   => oled,
        seg   => seg,
        segdp   => segdp,
        dip_sw   => (others => '0'),
        reset_n   => reset_n,
        clk_in   => clk_in

	);

end architecture MyHDL;
